# Generated by Django 3.2.15 on 2022-11-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('discription', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
                ('prize', models.CharField(max_length=100)),
                ('size_chart', models.CharField(max_length=250)),
                ('ct_id', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
