# Generated by Django 3.2.15 on 2022-11-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
    ]
